[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = ''
    alertText = 'Despite the trend in <a class="alert-link fw-normal" target="_blank" href="https://github.com/minio/minio/issues/21714">open</a> <a class="alert-link fw-normal" target="_blank" href="https://blog.localstack.cloud/the-road-ahead-for-localstack/">source</a> <a class="alert-link fw-normal" target="_blank" href="https://www.puppet.com/blog/open-source-puppet-updates-2025">software</a>, we made <a class="alert-link fw-normal" target="_blank" href="/blog/waha-community">WAHA free</a>! 🎉<p></p>To keep WAHA going, please <a class="alert-link fw-normal" target="_blank" href="/support-us"><b>🎁 Support Us</b></a> using the new <b>Community</b> tier (<b>$5/mo</b>) on <a class="alert-link fw-normal" target="_blank" href="https://www.patreon.com/wa_http_api/membership"><b>Patreon</b></a>, <a class="alert-link fw-normal" target="_blank" href="https://boosty.to/wa-http-api"><b>Boosty</b></a> or <a class="alert-link fw-normal" target="_blank" href="https://portal.devlike.pro/support-us"><b>Crypto</b></a> 🙏'

