[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = ''
    alertText = '<a class="alert-link fw-normal" target="_blank" href="/blog/waha-community">We made WAHA Plus free</a>! 🎉<p></p>To keep WAHA going, please <a class="alert-link fw-normal" target="_blank" href="/support-us"><b>🎁 Support Us</b></a> using the new <b>Community</b> tier (<b>$5/mo</b>) on <a class="alert-link fw-normal" target="_blank" href="https://www.patreon.com/wa_http_api/membership"><b>Patreon</b></a>, <a class="alert-link fw-normal" target="_blank" href="https://boosty.to/wa-http-api"><b>Boosty</b></a> or <a class="alert-link fw-normal" target="_blank" href="https://portal.devlike.pro/support-us"><b>Crypto</b></a> 🙏'

