[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = ''
    alertText = '<a target="_blank" class="alert-link stretched-link fw-normal" href="https://github.com/devlikeapro/waha/issues/1076">💵 $2,000 Bug Bounty – Help Secure WAHA!</a>'

